site_name: TXM-Lattice

site_url: https://wq2021.github.io/TXM-Lattice/

theme :
  name: material
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - Projects:
      - GGHF-TXM: gghf-txm.md