site_name: TXM Lattice

site_url: https://lattice-8094.github.io/txm-lattice/

theme :
  name: material
  language: fr
  favicon : assets/images/favicon.png
  logo: assets/images/lattice_carre.png
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Accueil: index.md
  - Corpus :
      - GGHF: gghf-txm.md